# Generated by Django 5.2.8 on 2025-11-22 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_prescription', models.ImageField(upload_to='aid/prescriptions/')),
                ('income_proof', models.ImageField(upload_to='aid/income_proof/')),
                ('reason_for_aid', models.TextField()),
                ('shipping_address', models.TextField()),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=100)),
                ('tracking_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved - Pay Shipping'), ('PAID', 'Shipping Paid'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_applications', to=settings.AUTH_USER_MODEL)),
                ('requested_medicines', models.ManyToManyField(blank=True, to='inventory.inventoryitem')),
            ],
        ),
    ]
